# Generated by Django 3.0.7 on 2021-07-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylang',
            name='lang',
            field=models.CharField(choices=[('de', 'Deutsch'), ('ru', 'Pусский'), ('hi', 'हिंदी द्वारा'), ('AR', 'عربي')], max_length=6),
        ),
        migrations.AlterField(
            model_name='productlang',
            name='lang',
            field=models.CharField(choices=[('de', 'Deutsch'), ('ru', 'Pусский'), ('hi', 'हिंदी द्वारा'), ('AR', 'عربي')], max_length=6),
        ),
    ]
