# Generated by Django 3.0.7 on 2021-08-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210711_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Türkçe'), ('de', 'Deutsch'), ('ar', 'Arabic')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('de', 'Deutsch'), ('ar', 'Arabic')], max_length=6),
        ),
    ]
