# Generated by Django 3.0.7 on 2021-09-07 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210801_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=190)),
                ('subject', models.CharField(max_length=120)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
